### ISSUE TITLE
Plugin causing my app to close without warning

### ISSUE THREAD

**Issue by rolinger** [cordova-sms/cordova-sms-plugin#113] opened 2016-11-18 23:17 UTC
I got an unusual issue, I implemented cordova-sms-plugin and it works....Bbbuuttt...its causing my app to crash.

1)  using `android: { intent: 'INTENT' } - is crashing my app without warning, and without any error messages.   It does open the default message app, populates the message and allows me to send it.  But after the message has sent A) it does not direct me back to my app and B) I manually try to switch back to my app only to see that it has been shut down (possibly why its not switching back).

Another side affect - is that when my app gets auto-closed, the default messaging app gets hung up for a bit...gets real slow and very unresponsive.  Especially if I cancel out of sending the message.

2)  When I use `android:{ intent: '' } - it works just fine.

Platform versions:
ionic: 1.7.16
cordova: 6.3.1
Android platform: 5.2.2
SMS v: 0.1.11

Here is my code to send the text message:
```
    var options = {
      android: {
        intent: 'INTENT'
      }
    }
    var success = function() { 
      $scope.msgColor = "green" ;
      $scope.messageSent = "Your message has been sent. Please wait for confirmation" ;
      $timeout(function() {
        $scope.messageSent = "" ;
      },5000) ;
    }
    var error = function() {
      $scop.msgColor = "red" ;      
      $scope.messageSent = "Error sending text message.  This number may not accept SMS messages" ;
      $timeout(function() {
        $scope.messageSent = "" ;
      },5000) ;
    }
    sms.send($scope.coPhone,msg,options,success,error) ;
```

**Comment by rolinger** [comment] 2016-11-19 00:06
Hmmmm...upon further reading I tested the 'intent' - I changed it to: `android: { intent: ''} `  -- in Android the text just auto-sent.  Guess I didn't fully understand what 'intent' does...and my app didn't crash.  

However, I believe the `android: {intent: 'INTENT'}` needs to be looked into as it is causing my app to crash.

**Comment by dbaq** [comment] 2016-11-28 17:21
Please run `adb logcat` on your machine to give me the android stacktrace. That's the only way I can help you.

Thanks.

**Comment by dbaq** [comment] 2016-12-13 21:25
Closing this once since no answer. Feel free to reopen it.

**Closed as completed by dbaq** 2016-12-13 21:25 UTC
Labels: needs reply, android

**Comment by princeJio** [comment] 2017-07-17 12:45
Hi @dbaq i got the same issue App crashes as soon as send sms using this plugin with intent:"INTENT"

ADB LOGS AFTER CRASH

07-14 10:15:11.773 249 264 I Ext4Crypt: No master key, so not ext4enc
07-14 10:15:12.056 860 3246 I chatty : uid=1000(system) Binder_B expire 2 lines
--------- beginning of crash
07-14 10:15:12.497 4649 4649 E AndroidRuntime: FATAL EXCEPTION: main
07-14 10:15:12.497 4649 4649 E AndroidRuntime: Process: com.harman.obd, PID: 4649
07-14 10:15:12.497 4649 4649 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.harman.obd.OBDService@8394b92 with Intent { cmp=com.harman.obd/.OBDService }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
07-14 10:15:12.497 4649 4649 E AndroidRuntime: at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3027)
07-14 10:15:12.497 4649 4649 E AndroidRuntime: at android.app.ActivityThread.-wrap17(ActivityThread.java)
07-14 10:15:12.497 4649 4649 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
07-14 10:15:12.497 4649 4649 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:102)
07-14 10:15:12.497 4649 4649 E AndroidRuntime: at android.os.Looper.loop(Looper.java:148)
07-14 10:15:12.497 4649 4649 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:5417)
07-14 10:15:12.497 4649 4649 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
07-14 10:15:12.497 4649 4649 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-14 10:15:12.497 4649 4649 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-14 10:15:12.497 4649 4649 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
07-14 10:15:12.497 4649 4649 E AndroidRuntime: at com.harman.obd.OBDService.onStart(OBDService.java:94)
07-14 10:15:12.497 4649 4649 E AndroidRuntime: at android.app.Service.onStartCommand(Service.java:459)
07-14 10:15:12.497 4649 4649 E AndroidRuntime: at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
07-14 10:15:12.497 4649 4649 E AndroidRuntime: ... 8 more
07-14 10:15:14.497 860 871 I chatty : uid=1000(system) Binder_2 expire 4 lines
07-14 10:15:14.519 860 878 I chatty : uid=1000(system) android.display expire 1 line
07-14 10:15:15.169 860 1342 I chatty : uid=1000(system) WifiService expire 1 line
07-14 10:15:15.815 860 4089 I chatty : uid=1000(system) Binder_F expire 2 lines
07-14 10:15:17.379 860 1404 I chatty : uid=1000(system) Binder_3 expire 10 lines
07-14 10:15:19.172 4914 4914 E AndroidRuntime: FATAL EXCEPTION: main
07-14 10:15:19.172 4914 4914 E AndroidRuntime: Process: com.harman.obd, PID: 4914
07-14 10:15:19.172 4914 4914 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.harman.obd.OBDService@8394b92 with Intent { cmp=com.harman.obd/.OBDService }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
07-14 10:15:19.172 4914 4914 E AndroidRuntime: at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3027)
07-14 10:15:19.172 4914 4914 E AndroidRuntime: at android.app.ActivityThread.-wrap17(ActivityThread.java)
07-14 10:15:19.172 4914 4914 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
07-14 10:15:19.172 4914 4914 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:102)
07-14 10:15:19.172 4914 4914 E AndroidRuntime: at android.os.Looper.loop(Looper.java:148)
07-14 10:15:19.172 4914 4914 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:5417)
07-14 10:15:19.172 4914 4914 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
07-14 10:15:19.172 4914 4914 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-14 10:15:19.172 4914 4914 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-14 10:15:19.172 4914 4914 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
07-14 10:15:19.172 4914 4914 E AndroidRuntime: at com.harman.obd.OBDService.onStart(OBDService.java:94)
07-14 10:15:19.172 4914 4914 E AndroidRuntime: at android.app.Service.onStartCommand(Service.java:459)
07-14 10:15:19.172 4914 4914 E AndroidRuntime: at

**Comment by rolinger** [comment] 2017-07-17 14:04
@dbaq - Sorry...I never your reply to my original issue.  I believe my fix was to remove: INTENT.  It's been a while.   Oddly enough, I am actually in the middle of testing code to remove the sms plugin as I am now going to relay all text messaging through my backend API so I can track all communications and send text messages through a 3rd party service.  SMS worked fine, but my app's needs changed.

**Comment by coolbeatz71** [comment] 2017-10-27 07:19
@dbaq. I am facing a big problem. The app crash when sending sms using intent:''. I am testing it on android 5.1.1(real device).

**Comment by dbaq** [comment] 2017-10-27 15:40
Are you using the latest version of this plugin?

**Comment by coolbeatz71** [comment] 2017-11-03 10:16
Yes, but I try to use only intent:"INTENT" but I remarked that its consuming airtime for sending sms, does the use of intent:"" also consume users airtime (I mean data bundle)?

**Comment by dbaq** [comment] 2017-11-03 22:01
What do you mean by airtime? (or data bundle?)

**Comment by coolbeatz71** [comment] 2017-11-05 18:27
its consumming credit of the users. The airtime is the money amount needed
for calling or sending sms with a phone. I was looking for a way of sending
the confirmation token to user to activate their account but when trying to
send sms to myself I remarked that its consumming my airtime. Briefly this
is the amount that are charged by a Network Provider like orange or MTN for
each call or each sms.

**Comment by RCrizt12** [comment] 2020-02-07 01:44
need help. My app also crash when sending sms using option intent:''.  I am using the latest version.

**Comment by RCrizt12** [comment] 2020-02-07 03:15
option { intent:'' }
--------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
    Process: org.cordova.quasar.app, PID: 25360
    java.lang.SecurityException: Neither user 10214 nor current process has android.permission.READ_PHONE_STATE.
        at android.os.Parcel.readException(Parcel.java:1951)
        at android.os.Parcel.readException(Parcel.java:1897)
        at com.android.internal.telephony.ISms$Stub$Proxy.sendTextForSubscriber(ISms.java:867)
        at android.telephony.SmsManager.sendTextMessageInternal(SmsManager.java:330)
        at android.telephony.SmsManager.sendTextMessage(SmsManager.java:313)
        at com.cordova.plugins.sms.Sms.send(Sms.java:192)
        at com.cordova.plugins.sms.Sms.access$400(Sms.java:22)
        at com.cordova.plugins.sms.Sms$1.run(Sms.java:102)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
D/CordovaActivity: Paused the activity.
I/Process: Sending signal. PID: 25360 SIG: 9
Process 25360 terminated.
