### ISSUE TITLE
iPhone 6, 8.2 Input & Keyboard Disappear

### ISSUE THREAD

**Issue by jermahs** [cordova-sms/cordova-sms-plugin#22] opened 2015-03-17 16:15 UTC
Just installed the cordova-sms-plugin and love it. However, I noticed an issue where the input and keyboard disappear almost instantly when it shows the native iMessage screen. It's there, flickers and disappears. If I then click on the input field to add contacts it'll come back showing the message I am trying to send and the keyboard. 

Has anyone else run into this issue? Any resolution?

My options are the default suggested per the README.

**Comment by dbaq** [comment] 2015-03-17 16:34
hey @jpgilchrist,

Thanks for the feedback. I've never experienced this issue in the past. Unfortunately I don't have any iPhone 6 to test where I am right now. Have you been able to reproduce the issue on other iPhones (5,6+)? Or other iOS versions?

@aharris88 do you have an iPhone 6 to test please?

**Comment by agarrharr** [comment] 2015-03-17 16:35
I can test on an iPhone 5.

**Comment by bnockerts** [comment] 2015-03-17 16:37
I'm running into this same issue on an iPhone 5s running iOS 8.1. The interesting thing is that it works fine if I just provide a message with no phone number. When I use the plugin with a phone number the message flickers and disappears.

**Comment by jermahs** [comment] 2015-03-17 20:21
Unfortunately, we don't have an iPhone 5S or lower to test on at the moment. If I get my hands on one in the next few days, I'll update the thread.

**Comment by dbaq** [comment] 2015-03-23 19:09
Hey guys, I wasn't able to reproduce the error on an iPhone 5S iOS 8.1.3 (12B466).

Can you guys try on a simple cordova app? (trying to reduce the scope)

here is the code I used:

```
    sendSms: function() {
        var number = document.getElementById('numberTxt').value;
        var message = document.getElementById('messageTxt').value;

        var opts = {
            replaceLineBreaks: true,
            android: {
                intent: 'INTENT'
            }
        };
        var success = function () { alert('Message sent successfully'); };
        var error = function (e) { alert('Message Failed:' + e); };
        sms.send(number, message, opts, success, error);
    }
```

```
    <body>
        <div class="app">
            <h1>Apache Cordova</h1>
            <div id="deviceready" class="blink">
                <p class="event listening">Connecting to Device</p>
                <p class="event received">Device is Ready</p>
            </div>

            <input name="" id="numberTxt" placeholder="Enter mobile number" value="" type="tel" />
            <textarea name="" id="messageTxt" placeholder="Enter message">test</textarea>
            <input type="button" onclick="app.sendSms()" value="Send SMS" />
        </div>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="js/index.js"></script>
    </body>
```

**Comment by robertervin** [comment] 2015-03-25 23:06
@dbaq I am using angularjs + ionic + cordova, and using the ngcordova wrapper for this plugin. I am getting the same error described above with the following phones/errors:

`iPhone 6+ iOS8` / `iPhone 6+ iOS8` / `iPhone 5C iOS8` - Screen flicker w/ keyboard, then keyboard disappears until phone # input box is selected, then it returns as normal. It should be noted that this only happens after Messaging is loaded once. The first time the phone loads Messaging it works great. After that load, even if the app is closed then reopened, it has this issue.

`iPhone 5S iOS7` - Full keyboard at launch w/ input message, then drops out of screen for about 0.25 seconds before returning as just the message + "send" button. keyboard is restored as normal after clicking on text input.

**Comment by agarrharr** [comment] 2015-03-27 17:49
To be honest, I'm probably not going to find the time to test on an iPhone.

**Comment by dbaq** [comment] 2015-03-29 19:08
@RobertErvin, I tried again but I can't reproduce. Can you try with a simple cordova app + sample code of the plugin please?

side question: are you using ionic keyboard for your project? (https://github.com/driftyco/ionic-plugins-keyboard)

**Comment by jnorris441** [comment] 2015-04-07 00:41
@RobertErvin  Change animated:YES to NO in SMS.m

**Comment by dbaq** [comment] 2015-04-07 17:04
Let me know if it fixes the issue, I will apply the changes on master.

**Comment by icanb** [comment] 2015-04-14 17:48
Changing animated:YES to NO in SMS.m worked for me as well, but it looks a little ugly.

**Comment by ictliujie** [comment] 2015-07-21 12:35
we had the same problem on send sms in hybrid-way, and the solution is also change animated:YES to NO. What's more, the problem is properly the fault of webview,  if you present the send-sms-controller from a normal viewcontroller other than webview, you would not run into this issue.

**Comment by dbaq** [comment] 2015-08-27 22:03
do you guys still have the issue? even with the latest webviews available?

**Comment by DaDanny** [comment] 2015-09-02 22:40
I have been experiencing the same issue with the keyboard and input disappearing from iMessage on iOS and it will reappear once the user clicks the numbers/contact section.

Changing Animated to NO, helped with the issue, but now if I am messaging someone who I have had an ongoing conversation with, a gap is introduced between the bar which says "New Message     Cancel" and the bar which has the "To: {{contacts}}"

**Comment by dbaq** [comment] 2015-09-02 22:50
which webviews are you guys using? I am still unable to reproduce.

**Comment by okonon** [comment] 2015-09-15 02:36
@dbaq how do i check the webview version?

**Comment by okonon** [comment] 2015-09-15 04:32
having same issue here on multiple devices

```
Cordova CLI: 5.1.1
Gulp version:  CLI version 3.8.11
Gulp local:  
Ionic Version: 1.0.0
Ionic CLI Version: 1.6.1
Ionic App Lib Version: 0.3.3
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.4
Xcode version: Xcode 7.0 Build version 7A218 
```

no issue on following setup:

```
ionic info

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 6.3.2 Build version 6D2105 
```

**Comment by okonon** [comment] 2015-09-15 06:08
@dbaq now my good device is getting same issue with following erorr from the plugin:

```
[Error] "Message cancelled."
    (anonymous function) (console-via-logger.js, line 173)
    (anonymous function) (controllers.js, line 2134)
    callbackFromNative (cordova.js, line 293)
    (anonymous function) (cordova.js, line 1107)
    nativeEvalAndFetch (cordova.js, line 1115)
    nativeCallback (cordova.js, line 1104)
    global code (index.html, line 1)
```

screen flashes with native sms ui and closes immediately

**Comment by okonon** [comment] 2015-09-15 06:58
for those who is struggling with this issue, turns out there was a bug in my code that forceclosed native SMS ui. All double check your code.

**Comment by dbaq** [comment] 2015-09-18 17:34
@softBarbarian, what do you mean exactly by "force closed native SMS ui", could you give more details please?

**Comment by hugobast** [comment] 2015-10-01 00:57
@softBarbarian I just used this for the first time ever in an Ionic project: `$cordovaSms.send 'number', 'message'` I'm not closing anything.

**Comment by hugobast** [comment] 2015-10-01 01:15
This isn't clear from my previous answer but I believe this legitimately needs to be looked into. First time it works but if you cancel out and use the SMS again the keyboard flickers and disappears. I have to tap into the `To:` field for it to show up again.

**Comment by narenpublic** [comment] 2016-01-28 08:00
Yes I am seeing the same thing as @hugobast.  If you cancel the SMS, the keyboard doesn't show the next time.

**Comment by okonon** [comment] 2016-01-28 20:12
i figured it out, there was a syntax error in the code when i was building message text and it was closing native send sms modal window.

**Comment by randyhongo** [comment] 2016-02-29 03:16
I am seeing the same behavior in iOS where when I first send a text everything works correctly.  If I attempt to send a subsequent text the keyboard does not display unless I tap in to the To: field as @hugobast mentioned.  Any ideas on how to fix this?

**Comment by msalcala11** [comment] 2016-03-14 05:32
Experiencing the same issue as @hugobast, @randyhongo, and @narenpublic. Has anyone figured out a fix?

**Comment by sebahattint** [comment] 2016-04-20 13:13
I had same problem. I changed animated:YES to NO (Sms.m Line 45 and 76) and worked for me.Thanks..

**Comment by darwind** [comment] 2016-05-11 19:59
Experiencing the same issue, but apparently it randomly appears.

Tested on an iPhone 6 with iOS 9.2.1, an iPhone 6 with iOS 9.3.1 and an iPad Air 2 with iOS 9.3.1. All devices suffer from this weird issue, but not always. I've managed to see the message show sometimes.

**Comment by NoName-gy** [comment] 2016-05-24 06:58
Same issue, change animated:YES to NO work for me. thanks.

**Comment by mzahidriaz** [comment] 2016-05-28 09:44
Same issue, change animated:YES to NO work for me. thanks.

**Comment by sneps85** [comment] 2016-10-24 12:44
Same issue here

**Comment by MattDHill** [comment] 2016-11-15 15:18
Changing animated: YES to NO no longer solves the problem in iOS 10. Doing so changes the behavior slightly, but if the user attempts to scroll up through the conversation, the input section still disappears beneath the viewport. Also, on a second attempt to open SMS, the input section fails to open at all. It gets about half way, then drops back beneath the view port. In either case, the user can make it re-appear by clicking the To: field, but I don't think most people will figure this out...

**Comment by Andoion** [comment] 2016-12-14 14:54
Same issue as @MattDHill

**Comment by justinmaltese** [comment] 2017-06-04 21:43
For anybody using ionic - calling the close() method of the [ionic-keyboard plugin](https://github.com/ionic-team/ionic-plugin-keyboard) in both the sms success and error handlers served as a workaround for me.

**Comment by MattDHill** [comment] 2017-06-11 09:36
@justinmaltese I'm using Ionic 3 and your suggestion is not working. If I call sms.send(), then cancel, then call sms.send() again, the keyboard does not show. It tries to, get about halfway open, then closes. To clarify, the keyboard only shows on the first attempt and fails thereafter. @dbaq any ideas here?

**Comment by yeisson** [comment] 2017-07-11 18:40
Same issue as @MattDHill, i'm using Ionic 3, the keyboard only shows on the first attempt. any workaround?

**Comment by marcogrieco** [comment] 2017-07-31 12:41
Hi, same issue for me with Ionic 3. The keyboard disappear after first attempt. Any ideas?

**Comment by meggillespie** [comment] 2017-08-11 23:12
Is there any more information on this issue? 

I'm getting the same result.
Deploy app through Xcode initial call to send sms launches SMS dialog and keyboard opens....send, cancel or error initial msg...next attempt to call send.sms... SMS dialog opens while the keyboard disappears. It's very peculiar behaviour. Is this a Cordova or Ionic issue? @dbaq  @jgw9 

Cordova CLI: 7.0.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.10.0
Xcode version: Xcode 8.3.1 Build version 8E1000a

**Comment by jermahs** [comment] 2017-08-21 13:29
@dbaq I'm not working on a project using this anymore at this time. I was doing a clean up of some issues of mine and came by this one. Please do not wait for my reply.

**Comment by eonardol** [comment] 2017-09-29 07:10
Same issue for us using iOS 11 on Ionic v.1
We have solved using a `setTimeout` (or `$timeout`) when calling the function that triggers the sending of the sms.

**Comment by dijitalbrains** [comment] 2017-09-29 13:27
@eonardol You mean you're firing $cordovaSms.send(); with some delay and it doesnt hide the keyboard anymore ?

**Comment by eonardol** [comment] 2017-10-02 08:24
yes @usman33, for e.g.:
 
    vm.doIt = function () {
        // ... set to, sms text,...
        $timeout(function() {
           sms.send(to, smsText, options, success, error);
        }, 500);
    };

**Comment by dijitalbrains** [comment] 2017-10-02 08:58
Great! thankyou.. it works for me as well.

**Comment by meggillespie** [comment] 2017-10-17 23:10
I can confirm @eonardol solution works for me as well.

**Comment by sssalib42** [comment] 2017-10-18 00:55
setTimeout worked on Ionic 3 and iOS 11! Thanks.

**Comment by ivopashov** [comment] 2017-10-23 20:26
I observe this behavior also and think that has something to do with using the `tappable` directive. Having it breaks things (but action is immediate), not having it is fine (but click is 300 ms delayed). When i removed `tappable` from my views fixed things. I guess for the same reason the `timeout` hack proposed by @eonardol works. Just ionic/sms plugin can't handle for some weird reason the immediate calls.

**Closed as completed** 2019-03-21 03:42 UTC
Labels: needs reply
