### ISSUE TITLE
Expected 2-3 arguments but not 5

### ISSUE THREAD

**Issue by vincebanzon** [cordova-sms/cordova-sms-plugin#148] opened 2017-09-22 08:31 UTC
Hi, I've been working on this plugin and other plugins for SMS. So far, this plugin is working among all others. 
However, I can't catch the activity if it is successfully sent or not when user CANCELS the message from an INTENT for android, ios and windows.
```
           options = {
             android: {
               intent: 'INTENT'
             }
           };

           sms.send(number, message, this.options).then(
             sent => {
               console.log("Message success");
             }, error => {
               console.log("Message failed");
             }
           );
```

The above code works. 
Base on the documentation, I can use 5 parameters :

```           sms.send(number, message, options, success, error). ```

But I can't add success and error since it only accepts 2-3 parameters. 
I get an error: "[ts] Expected 2-3 arguments, but got 5."
How do I add this 2 more parameters?

**Comment by vincebanzon** [comment] 2017-09-22 08:36
any thoughts on this @dbaq ? :-)

![untitled](https://user-images.githubusercontent.com/11060486/30736594-f57c2002-9fb5-11e7-8fb6-5d541c212829.png)

**Comment by dbaq** [comment] 2017-09-22 19:12
hey @vincebanzon,

>However, I can't catch the activity if it is successfully sent or not when user CANCELS the message from an INTENT for android, ios and windows.

You should be able to do it on iOS. On android you can't because the Intent does not return a specific code,  we don't know it is a success or not.

> Base on the documentation, I can use 5 parameters :
>
> sms.send(number, message, options, success, error).
>
> But I can't add success and error since it only accepts 2-3 parameters.
> I get an error: "[ts] Expected 2-3 arguments, but got 5."
> How do I add this 2 more parameters?

Which typescript file are you using?

**Comment by vincebanzon** [comment] 2017-09-25 05:30
Thanks for the response @dbaq .
However, I can't do it on iOS. I can only use 3 arguments. 

> Which typescript file are you using?
I'm not sure which typescript I am using. Ionic 3 already uses typescript.

**Comment by SpellChucker** [comment] 2017-12-12 19:05
@dbaq @vincebanzon The issue is related to how it's defined in the `ionic-native` repo. See lines here: https://github.com/ionic-team/ionic-native/blob/995fd56894234c9cdb0f9e873822d12313aa6e88/src/%40ionic-native/plugins/sms/index.ts#L68-L77

These need updating to allow you to pass callbacks as parameters in ionic apps using this plugin via ionic-native.

**Comment by dbaq** [comment] 2018-01-25 00:57
Thanks @SpellChucker for pointing this out. Closing this issue since it managed by the ionic team. If you are experiencing this issue please open an issue on the ionic-native repo. Thanks

**Closed as completed by dbaq** 2018-01-25 00:57 UTC
Labels: needs reply
