### ISSUE TITLE
SMS not supported on this platform

### ISSUE THREAD

**Issue by maxmayerhofer** [cordova-sms/cordova-sms-plugin#88] opened 2016-05-25 18:11 UTC
Hi, 
i have a little problem. I write an app to send sms, until SDK 21. And all works fine.
Now, i must update the App to support the ..."fantastic", permission-request of SDK 23 :/

So i updated my cordova version, cordova-android version, and the plugin. It compiles completely.

BUT: I havent a Device with SDK 23 (its much expensive :p) , so i would like to use the Emulator.
But when i try to use the App on the Emulator, he says "SMS not supported this platform".
The Emulator has the follow details:
`Name: Nexus_5_API_23
CPU/ABI: Google APIs Intel Atom (x86)
Path: /Users/maxmayerhofer/.android/avd/Nexus_5_API_23.avd
Target: Android 6.0 (API level 23)
Skin: nexus_5
SD Card: /Users/maxmayerhofer/.android/avd/Nexus_5_API_23.avd/sdcard.img
Snapshot: no
hw.lcd.density: 480
hw.dPad: no
avd.ini.encoding: UTF-8
hw.camera.back: none
disk.dataPartition.size: 200M
hw.gpu.enabled: yes
runtime.network.latency: none
skin.dynamic: yes
hw.keyboard: yes
runtime.network.speed: full
hw.device.hash2: MD5:2fa0e16c8cceb7d385183284107c0c88
hw.ramSize: 1536
tag.id: google_apis
tag.display: Google APIs
hw.sdCard: yes
hw.device.manufacturer: Google
hw.mainKeys: no
hw.accelerometer: yes
hw.trackBall: no
hw.device.name: Nexus 5
hw.sensors.proximity: yes
hw.battery: yes
AvdId: Nexus_5_API_23
hw.sensors.orientation: yes
hw.audioInput: yes
hw.camera.front: none
hw.gps: yes
avd.ini.displayname: Nexus 5 API 23
snapshot.present: no
vm.heapSize: 64
runtime.scalefactor: auto`

So because its fail I try it on a Emulator with SDK 21 and it fails also. And I Try on my Device with SDK21 and there it will works.

What can i do?

Sorry for my english.

**Comment by dbaq** [comment] 2016-05-26 20:28
It looks like a duplicate of https://github.com/cordova-sms/cordova-sms-plugin/issues/84, feel free to reopen this issue if it is not a duplicate.

**Comment by maxmayerhofer** [comment] 2016-05-26 21:57
Hi, 
thanks for the fast answer, so i think its not a duplicate :) 
My "Problem" is that i can't send SMS from any android-Emulator (Tested on SDK 23 and 21) . 

On a Device with SDK 21 i try it successfully, but i don't know the behavior on a SDK 23 device, because i haven't a Device with SDK23. 

So my Question:  How can a App who use the this plugin makes run on a emulator. 

PS: Nice Plugin 👍

**Comment by dbaq** [comment] 2016-05-26 22:27
hey @maxmayerhofer, you cannot send a SMS directly from the emulator. There is nothing you can do except testing on a real device. Your best shot is to build an APK and send it to one of your friends with a recent android device.

**Closed as completed by dbaq** 2016-05-26 22:27 UTC
