### ISSUE TITLE
Support for MMS attaching image?

### ISSUE THREAD

**Issue by rolinger** [cordova-sms/cordova-sms-plugin#162] opened 2018-01-24 19:35 UTC
Hi..i read various comments, quite old, about adding support for images and multiple people.

I am using Android native sms app...once in there the user can add as many users as they like.  But can I auto-add an image attachment to the message?  In addition, can that file be specific image already bundled in the app (say from the root/img folder....or would I need to store the file else where within the app?  I would use plugin-file to retrieve the image and attached (I think).

The same for iOS...but it already forces the use of the native composer.  The issue is just about attaching the image at that point.

If this is done or addressed, please point me in the right direction.

**Comment by dbaq** [comment] 2018-01-25 00:47
hello @rolinger, thanks for your post. In order to have attachments like images, we need to add MMS support. It is being discussed here #14. We are looking for contributors to add MMS support, feel free to comment on the issue if you would like to contribute.

Closing this once since it is a duplicate of #14.

**Closed as completed by dbaq** 2018-01-25 00:47 UTC
