### ISSUE TITLE
SMS does not appear in messaging app, but it is sent

### ISSUE THREAD

**Issue by demobiel** [cordova-sms/cordova-sms-plugin#193] opened 2019-03-11 08:16 UTC
Hi

We have a very small tool that actually listens to PusherJS, and on any incoming message tries to send a sms.
If we send sms in bulk, which means many requests arrive via PusherJS, we are able to send the sms's and we get a success callback from the plugin, but not all messages are visible in the messaging app. So we are sending probably messages in parallel, and maybe the messaging app does not allow that.

They use the default messaging app installed on the Android device.

It is also so that after some time, some of the messages suddenly pop up in the messaging app.

I guess this might not be a problem of the plugin, but more the messaging app that is not able to follow, or is there a way we could force the messaging app to refresh? Or do I have to refactor my code to push any incoming pusher messages into a queue and send the queue one by one?

Kind regards

Andries

**Comment by demobiel** [comment] 2019-03-11 10:10
update: it actually only occurs when we try to send multipart messages (so the content is longer and does not fit into one message). I see in SMS.java that in that case a different way of sending is used, and i have the feeling that it takes much longer to send the message. It is even so that the messaging app blocks at that moment. 

I think the problem is not with the plugin, but with the default messaging app.

**Comment by dbaq** [comment] 2019-03-21 03:28
Hi @demobiel,

Sorry for the late reply. 

- Have you figured this out?
- Were you able to reproduce? 
- Which default messaging app? You can change the default app.
- Do you experience the same issue if send SMS < 140?

**Comment by dbaq** [comment] 2019-05-29 22:07
Closing this one since no reply. Feel free to reopen it.

**Closed as completed by dbaq** 2019-05-29 22:07 UTC
Labels: needs reply, android
