### ISSUE TITLE
Is it possible to send multiple people sms on iOS?

### ISSUE THREAD

**Issue by cmosboss** [cordova-sms/cordova-sms-plugin#112] opened 2016-11-16 01:57 UTC
I am having a lot of issues with iOS. Originally I set it all up on android and it worked great (sending group message, loop through and send out sms messages with no intent etc) But apparently iOS cannot do this? And on top of that technically group messages are considered MMS and also do not work? Any info on how to send out a text to 2-4 people via iOS would be great.

**Comment by lordgreg** [comment] 2016-11-16 13:22
Hi. Yes it is. Just use `comma` to split the numbers:

```
sms.send('+49123, +3861234, 1337...', this.data.message
```

👍

**Comment by cmosboss** [comment] 2016-11-16 15:53
So I just tested this exactly how you wrote it, I basically took out all my logic to get the number in the program and just typed out 2 numbers back to back with the +xxxxxxxx then a comma and it did not work. It acts like it is opening a group chat but the text is off to the side and the numbers are somehow messed up. View my image below, it seems to open a MMS instead of an SMS and the formatting is all off. 
http://i.imgur.com/XexLWVn.jpg

Edit, here is a copy of my exact code, with numbers changed for privacy obviously (note that this works great for single numbers)

```
var options = {};
var success = function () { console.log('Message sent successfully'); };
var error = function (e) { console.log('Message Failed:' + e); };
sms.send('+15555555555, +15555555555', message, options, success, error);
```

**Comment by cmosboss** [comment] 2016-11-17 19:42
@dbaq Any ideas? I have tried everything I can think of, everytime I open a new MMS the keyboard / text area area all kinds of broken. iOS 10.2 if that helps.

**Comment by lordgreg** [comment] 2016-11-17 20:00
Have you tried it on any other device? How does your message string look like? You also never told device, ios version, cordova version installed etc?

**Comment by cmosboss** [comment] 2016-11-17 20:04
@lordgreg message is a predefined string in this case "Hi", ios is 10.2. Cordova 6.3.1, Ionic 1

**Comment by dbaq** [comment] 2016-11-18 04:57
Hey @lordgreg, @zocheyado,

that's interesting, could the formatting issue be related to #22?

> it seems to open a MMS instead of an SMS

that's the expected behavior, if you want to send several SMS (instead of one MMS), you should iterate over your phone numbers array and call `send` multiple times.

Side note, I should review the public API of this plugin to be more simple to use and allow both behaviors.

**Comment by lordgreg** [comment] 2016-11-18 07:11
Hi @dbaq. Thank you for your feedback. I'm not sure this is the workflow I want then,... having 10 contacts I want to send a simple message to all of them. Calling `send` multiple times would open 10 message windows... so I thought from reading the api :)

I must say though, everything is working superb as-is;

Good job 👍

**Comment by cmosboss** [comment] 2016-11-18 16:47
@dbaq Lordgreg is correct, iterating over the numbers works great for android because you can send them without opening a sms box but  because of how iOS opens a messaging app MMS is the only way it can work. Also I think it could be related to #22 however I tried the fix in that thread and it is not working, in that thread someone comments on how it no longer works on iOS 10

**Comment by dbaq** [comment] 2016-11-18 16:52
I tried on iPhone last night with the latest iOS 10, I wasn't able to reproduce any layout issue. I never have been able to reproduce #22.

@lordgreg, it is an iOS limitation, there is nothing I can do on my side. If you really need to invite 10+ contacts, you should go for a solution like Twilio and send SMS via their service (the sender won't be a known number though)

**Comment by cmosboss** [comment] 2016-11-18 16:54
@dbaq Do you use regular cordova or ionic? Just wondering since I am using ionic and so was the user in #22, I wonder if it is related to that. Do you have any suggestions for me on how to find the source / fix the formatting issue? I know some Objective-C so maybe if you can point me to the area where the plugin invokes the messaging app I can take a look.

**Comment by dbaq** [comment] 2016-11-18 17:02
@zocheyado pure js in a simple cordova app (that's the easiest way to know if an issue comes from the plugin or something else). Have you tried to remove ionic keyboard? 

You need to look at this code https://github.com/cordova-sms/cordova-sms-plugin/blob/master/src/ios/Sms.m#L45-L89

**Comment by cmosboss** [comment] 2016-11-18 17:21
@dbaq I just tried removing ionic keyboard and no luck still caused issues. Seems very odd that it is off to the side like it is. Anyways I will let you know if I find anything in the sms.m file.

**Comment by dbaq** [comment] 2016-12-13 21:25
Closing this once since no answer. Feel free to reopen it.

**Closed as completed by dbaq** 2016-12-13 21:25 UTC
Labels: iOS

**Comment by aliabbas12** [comment] 2018-02-04 04:59
I know this is an old thread but in case if any body else wants to know this for future reference:

On IOS if you want to send the SMS to multiple people. you have to append the numbers with a comma at the end.

for instance: 12345,34567,23456 will not work. it only takes first 2 numbers
Solution: 12345,34567,23456,  <- this will work fine. as IOS then takes the full list.

Hope this will help anyone else looking to do it on IOS.
Android side should work just by looping through the numbers
