### ISSUE TITLE
[Android] Update PendingIntent creation for apps targeting android 12+

### ISSUE THREAD

**Issue by jlebras** [cordova-sms/cordova-sms-plugin#229] opened 2022-04-19 13:57 UTC
Applications targeting Android 12+ crash on PendingIntent creation, on Android 12+.
Pending intents must specify either FLAG_IMMUTABLE or FLAG_MUTABLE:
> Up until Build.VERSION_CODES.R, PendingIntents are assumed to be mutable by default, unless FLAG_IMMUTABLE is set. Starting with Build.VERSION_CODES.S, it will be required to explicitly specify the mutability of PendingIntents on creation with either (@link #FLAG_IMMUTABLE} or FLAG_MUTABLE. It is strongly recommended to use FLAG_IMMUTABLE when creating a PendingIntent. FLAG_MUTABLE should only be used when some functionality relies on modifying the underlying intent, e.g. any PendingIntent that needs to be used with inline reply or bubbles.

**Comment by dbaq** [comment] 2022-04-21 21:01
Hi Julien! thanks for the report, please feel free to open a PR. I don't have much bandwidth at the moment to address this.

**Comment by RodinHaker** [comment] 2022-12-11 21:14
Hello, I have created a PR for this issue. I have manually edited this in my own application and it works as intended. You can find the PR here: #230

**Comment by abhishekdana1999** [comment] 2022-12-27 06:59
Was there any update on this

**Comment by RodinHaker** [comment] 2022-12-27 09:09
@abhishekdana1999 My PR has not yet been approved, I case you need this plugin now however, you can make the change yourself locally for now.

**Comment by dbaq** [comment] 2022-12-30 00:23
hey both, I merged the PR but won't be able to release a new version on npm until next week.

**Comment by dbaq** [comment] 2023-01-03 20:51
v.1.0.3 has been published. Thanks for the contribution @RodinHaker 🥂 

https://www.npmjs.com/package/cordova-sms-plugin/v/1.0.3

**Closed as completed by dbaq** 2023-01-03 20:51 UTC
