### ISSUE TITLE
sms not defined

### ISSUE THREAD

**Issue by rastalamm** [cordova-sms/cordova-sms-plugin#48] opened 2015-08-09 05:55 UTC
I keep getting a reference error in my console stating that sms can't be defined. 

All sms.js files are in the correct location. 

How can I troubleshoot and solve this?

**Comment by dbaq** [comment] 2015-08-12 04:06
are you using cordova? phonegap?

**Comment by rastalamm** [comment] 2015-08-12 08:08
Cordova version 5.1.1

In the docs you state it only works with Cordova 3.x and 4.x version.

Guess that is my issue

**Comment by dbaq** [comment] 2015-08-12 15:46
No it should work with cordova 5.1.1. Is your code executed after the device ready event has been fired? How are you testing your code? in a browser? in a simulator? or on a real device? android or iOS?

**Comment by rastalamm** [comment] 2015-08-12 19:55
Tested my code on Browser, real device, in Ionic view and in the simulator - not sure of the errors I am receiving in the simulator/device as I have no console. I am testing this out on an android. 

The code is wrapped in an $ionic.ready function.. Here is a gist of the controller I am using for this. 

https://gist.github.com/Rastalamm/3517e26193cd75ec0fb0

**Comment by dbaq** [comment] 2015-08-12 20:03
You can access the device console from `chrome://inspect` in chrome, your device must be connected via USB to your laptop. Let me know if you have the error on a real device.

**Comment by rastalamm** [comment] 2015-08-12 20:38
When I run it on my device hooked up to my computer, I get the original error.. 

ReferenceError: sms is not defined
    at Object.send (ng-cordova.js:2)
    at Scope.$scope.sendSms (sms-controller.js:2)
    at $parseFunctionCall (ionic.bundle.js:2)
    at ionic.bundle.js:4
    at Scope.$eval (ionic.bundle.js:2)
    at Scope.$apply (ionic.bundle.js:2)
    at HTMLButtonElement.<anonymous> (ionic.bundle.js:4)
    at HTMLButtonElement.eventHandler (ionic.bundle.js:2)
    at triggerMouseEvent (ionic.bundle.js:1)
    at tapClick (ionic.bundle.js:1)

**Comment by dbaq** [comment] 2015-08-12 20:43
did you follow that tutorial? http://ngcordova.com/docs/install/

**Comment by rastalamm** [comment] 2015-08-12 20:49
Yes, that is where I got the ionicPlatform.ready function from

**Comment by dbaq** [comment] 2015-08-12 20:54
what is the output of the following command in a terminal: `cordova plugin list`

**Comment by rastalamm** [comment] 2015-08-12 20:59
com.cordova.plugins.sms 0.1.4 "Cordova SMS Plugin"

**Comment by dbaq** [comment] 2015-08-12 21:02
Ok, I will try to reproduce your issue by using ngcordova in the following days unless you can share a minimalist project using ngcordova and reproducing the error?

**Comment by Rastalamm** [comment] 2015-08-12 21:09
Much appreciated!

**Comment by rastalamm** [comment] 2015-08-12 21:10
Much appreciated! Will try to put together something small for you to work on later today.

**Comment by dmarcos89** [comment] 2015-08-18 20:51
having the same issue... any idea why it could happen? thanks in advance!!

**Comment by rajeshwarpatlolla** [comment] 2015-08-24 12:02
I am also facing the same issue.

**Comment by dbaq** [comment] 2015-08-24 14:59
You guys are all using ng-cordova?

**Comment by rajeshwarpatlolla** [comment] 2015-08-24 15:01
@dbaq, if you have the solution please let us know.

**Comment by dmarcos89** [comment] 2015-08-24 15:02
hi, i found somewhere that most of the cordova functionalities do not work on ionic view. you only can test them if you have an android device or if you’re an apple developer.

**Comment by rajeshwarpatlolla** [comment] 2015-08-24 15:09
Yes, you are right @dmarcos89, thank you so much.

**Comment by dbaq** [comment] 2015-08-24 15:10
There are many solutions for the `sms not defined` issue, please answer the following questions, that will help me to reduce the scope of the problem:
- which version of cordova?
- which platform? ios? android?
- are you using ng-cordova?
- when are you getting the error? your browser? a simulator? a real device?
- what's the output of this command `cordova plugin list`
- are you calling the plugin after the deviceReady event has been fired?

**Comment by dbaq** [comment] 2015-08-27 22:00
Closing this one. If somebody has a `sms not defined`, make sure to check all the questions in my previous post.

**Closed as completed by dbaq** 2015-08-27 22:00 UTC
Labels: question, sms undefined

**Comment by NickAjderian** [comment] 2015-10-11 21:45
Can't check for typeof sms === 'undefined'

If i check for this i always get 'undefined'. But if I don't do the check, phonegap FINDS the sms object and sends the sms somehow. Strange!

```
    var msg='hello';
    //if(typeof sms === 'undefined' || typeof sms.send === 'undefined'){
    //  alert('SMS send is undefined. Would have sent ' + msg);
    //}else{
            sms.send('4412341234', msg, options, function () {
            }, function (e) {
                model.status = "Error checking in by SMS";
                alert('Failed to send SMS: ' + e);
            });
    //}
```

**Comment by netbuffer** [comment] 2015-11-28 01:58
http://stackoverflow.com/questions/31060722/cordova-refuse-to-execute-inline-event-handler-because-it-violates-the-followi

**Comment by ikomosin** [comment] 2016-01-25 15:12
I am developing PhoneGap App and I have faced with the same problem. ReferenceError: sms is not defined or if I am using window.sms it is null. after I have installed cordova-sms-plugin. regarding your questions:
1.    which version of cordova?
   D:\phonegap\sms>cordova -v
   5.4.1
   1.   which platform? ios? android?
      android
2.    are you using ng-cordova?
   I am using cordova
3.    when are you getting the error? your browser? a simulator? a real device?
   I am getting error in my cmd, after "phonegap serve" command, and connected with PhoneGap Developer App
4.    what's the output of this command cordova plugin list
   D:\phonegap\sms>cordova plugin list
   com.cordova.plugins.sms 0.1.7 "Cordova SMS Plugin"
   cordova-plugin-contacts 2.0.1 "Contacts"

I installed cordova-plugin-contacts just to make sure that all configured properly. cordova-plugin-contacts works for me fine.
1.    are you calling the plugin after the deviceReady event has been fired? 
   sure, I have put send sms event into deviceReady  section:
   bindEvents: function() {
       document.addEventListener('deviceready', this.onDeviceReady, false);
   },
   // deviceready Event Handler
   //
   // The scope of 'this' is the event. In order to call the 'receivedEvent'
   // function, we must explicitly call 'app.receivedEvent(...);'
   onDeviceReady: function() {
   
   ```
   var number = '+XXXXXXXXXXXX';
   var message = 'TEST';
   console.log(number);
   console.log(message);
   
   //CONFIGURATION
   var options = {
       replaceLineBreaks: false, // true to replace \n by a new line, false by default
       android: {
           intent: 'INTENT'  // send SMS with the native android SMS messaging
           //intent: '' // send SMS without open any other app
       }
   };
   
   var success = function () { alert('Message sent successfully'); };
   var error = function (e) { alert('Message Failed:' + e); };
   console.log('start1');
   window.plugins.sms.send(number, message, options, success, error);
   console.log('end');
   
   //app.receivedEvent('deviceready');
   ```
   
   }

[phonegap] [console.log] start1
[phonegap] [console.log] Error: Uncaught TypeError: Cannot call method 'send' of
 undefined
[phonegap] url: file:///data/data/com.adobe.phonegap.app/files/phonegapdevapp/ww
w/js/index.js

What files I have to check?

**Comment by dbaq** [comment] 2016-01-25 16:06
Hey,
You need to try on a real device. Also it is  `windows.sms.send` or `sms.send`, because `window.plugins.sms.send` won't work.

**Comment by ikomosin** [comment] 2016-01-25 16:19
Thanks for your fast reply. 
oh, sure, exactly I also tried with  windows.sms.send and sms.send, error is the same. So do I need to create app for android and install it without Phonegap Developer App? Right?

**Comment by dbaq** [comment] 2016-01-25 16:25
Yes. 

```
$ cordova platform add android
$ cordova run android
```

PS: I'd recommend to do not use phonegap. Use directly cordova or ionic-cli if you are using ionic.

**Comment by bboy-space** [comment] 2017-10-20 01:02
Hello ! 
Have the undefined message too. I have cordova 7.0.1, and well execute the code after deviceisready (in the process, othere plugins work)

here is my function : 
```
var sendSms: function() {
$('.contact').each(function(){	
	        var number = $(this).attr('data-phone'); /* iOS: ensure number is actually a string */
	        if( number != null && typeof number != "undefined" && number != ""){
	        	number = number.toString();
	        	alert('found ' + number);
		        var message = "lorem ipsum";
		        //CONFIGURATION
		        var options = {
		            replaceLineBreaks: false, // true to replace \n by a new line, false by default
		            android: {
		                //intent: 'INTENT'  // send SMS with the native android SMS messaging
		                intent: '' // send SMS without open any other app
		            }
		        };
		        windows.sms.send(number, message, options, function () { alert('Message sent successfully'); }, function (e) { alert('Message Failed:' + e); });
	        }

    	});
    }`
What should I do more ?
Thank you for your support

**Comment by abhishe3571** [comment] 2020-10-13 04:12
Hello anyone is here, some problem with smsReceive plugin.
I also get the same error that: Sms receive is not defined. Btw I used the Cordova Sms plugin and testing on the browser e.g.-google chrome.
and code is below(.ts file)
`start() {
    SMSReceive.startWatch(
      () => {
        console.log('watch started');
        document.addEventListener('onSMSArrive', (e: any) => {
          console.log('onSMSArrive()');
          var IncomingSMS = e.data;
          console.log('sms.address:' + IncomingSMS.address);
          console.log('sms.body:' + IncomingSMS.body);
          console.log(JSON.stringify(IncomingSMS));
          this.processSMS(IncomingSMS);
        });
      },
      () => { console.log('watch start failed') }
    )
  }

  stop() {
    SMSReceive.stopWatch(
      () => { console.log('watch stopped') },
      () => { console.log('watch stop failed') }
    )
  }

  processSMS(data) {
    const message = data.body;
    if (message && message.indexOf('enappd_starters') != -1) {
      this.OTP = data.body.slice(0, 6);
      console.log(this.OTP);
      this.OTPmessage = 'OTP received. Proceed to login'
      this.stop();
    }`
