### ISSUE TITLE
The main app closes when opening android's native message window

### ISSUE THREAD

**Issue by eamoto** [cordova-sms/cordova-sms-plugin#42] opened 2015-07-10 03:38 UTC
As stated above, when the android's native message window appears.. My app closes.. Please check my code below.

This is only happening on android. Not happening on iOS.

$scope.sendSMS = function(details) {
        var number = 'xxxxxxx';
        var message = "Some message here";

```
    var options = {
        replaceLineBreaks: false, // true to replace \n by a new line, false by default
        android: {
            intent: 'INTENT'  // send SMS with the native android SMS messaging
        //intent: '' // send SMS without open any other app
        }
    };

    var success = function () {
        //success code here
    };
    var error = function (e) {
        //error code here
    };
    sms.send(number, message, options, success, error);
}
```

**Comment by dbaq** [comment] 2015-07-19 17:04
Hello @eddieWh0,

That's the first time someone reports this kind of issue. Do you still have the issue? Have you tested on multiple devices? Are you sure about your configuration in the AndroidManifest.xml file? Are you using phonegap build?

Thanks

**Comment by eamoto** [comment] 2015-07-21 02:13
@dbaq I checked on several devices. And it seems that not working on some devices only. One device is Andriod 5.0 version.

**Comment by dbaq** [comment] 2015-07-22 17:12
@eddieWh0 have you tried with a basic cordova app? are you using something else than cordova?

**Comment by justinmasse** [comment] 2015-08-21 00:58
Experiencing the same issue on a Nexus 5, android version 5.1.1

**Comment by dbaq** [comment] 2015-08-27 22:06
@justinmasse and @eddieWh0, can you please share a codepen of your minimum code to isolate the issue please? I wasn't able to reproduce.

**Comment by dbaq** [comment] 2015-09-25 03:19
Closing this issue since I was not able to reproduce. If the issue persists, please share a codepen or a github repository for me to fork and reproduce the error.

**Closed as completed by dbaq** 2015-09-25 03:19 UTC
Labels: android

**Comment by graphicgeek** [comment] 2016-11-11 21:47
I'm having this issue, though it's not "closing" my app, so much as it is opening a version of the native messaging app inside the webview for my app. 

Here's my code:

```
var options = {android:{intent:'INTENT'}};

sms.send('12345', 'testing', options, function(){ console.log('sms success'); }, function(e){ console.log('sms error', e);})
```

This opens the native messaging app and I can even send the message, but after that I have no way to get the user back to my app. They have basically have to relaunch the app.

**Comment by dbaq** [comment] 2016-11-18 04:31
hey @graphicgeek, the only way I can help you is if you share the android stacktrace. You can obtain it by running `adb logcat` on your laptop while running the app on your phone.
