### ISSUE TITLE
plugin_not_instaled

### ISSUE THREAD

**Issue by marwanes** [cordova-sms/cordova-sms-plugin#101] opened 2016-09-29 15:51 UTC
i alredy instaled the plugin but it still doesn't work

**Comment by dbaq** [comment] 2016-10-06 18:18
Hello @marwanes,

can you please share more information? which platform? how did you install it? etc.

Thank you.

**Comment by vitaly87** [comment] 2016-10-10 13:06
I am using ionic 2.1.0 and cordova 6+ on  android

**Comment by dbaq** [comment] 2016-10-13 03:13
Might it be related to #103?

**Comment by dbaq** [comment] 2016-10-30 22:16
Closing this one since no answer, please reopen if the issue is still happening.

**Closed as completed by dbaq** 2016-10-30 22:16 UTC
Labels: needs reply, android
