### ISSUE TITLE
Why Cordova SMS plugin takes time to load for the first time?

### ISSUE THREAD

**Issue by maihannijat** [cordova-sms/cordova-sms-plugin#218] opened 2021-01-26 17:05 UTC
I am testing this on an iOS physical device. When I click on the button to send an SMS for the first time after a fresh installation, it takes up to 30 seconds to load, but after that, it happens instantly. Even after closing the application, and restarting the phone. I looked into the Log and found:

> file:xxxx/ios/capacitor-cordova-ios-plugins/sources/CordovaSmsPlugin/Sms.m: runtime: UI API called from background thread: -[UIViewController init] must be used from main thread only

```
sendSMS(phoneNumber: string, text: string, event) {
    this.sms.send(String(phoneNumber), text).then(result => {
        console.log(result);
    }).catch(error => {
        console.log(error);
    });
}
```

Angular version 11
IONIC version 5.31.1
SMS ionic-native/sms": "^5.31.1"
"cordova-sms-plugin": "^1.0.0"

**Comment by TravisHeaver** [comment] 2021-01-26 17:18
I believe this has been fixed in the WIP_MMS_support branch. The issue is the new view controller is created on a different thread: 
`        dispatch_async(dispatch_get_main_queue(), ^{
            [self.viewController presentViewController:composeViewController animated:YES completion:nil];
        });`
this could be fixed by creating the view controller inside the async thread. see the WIP_MMS_support, which was held of for other reasons. see #14

**Comment by maihannijat** [comment] 2021-01-26 17:48
@TravisHeaver Thanks for the reply. `dispatch_async` fixes the problem. I wrapped the whole block with the function. 

```
dispatch_async(dispatch_get_main_queue(), ^{

MFMessageComposeViewController *composeViewController = [[MFMessageComposeViewController alloc] init];
composeViewController.messageComposeDelegate = self;

NSString* body = [command.arguments objectAtIndex:1];
if (body != nil) {
    BOOL replaceLineBreaks = [[command.arguments objectAtIndex:3] boolValue];
    if (replaceLineBreaks) {
        body = [body stringByReplacingOccurrencesOfString: @"\\n" withString: @"\n"];
    }
    [composeViewController setBody:body];
}

NSMutableArray* recipients = [command.arguments objectAtIndex:0];
if (recipients != nil) {
    if ([recipients.firstObject isEqual: @""]) {
        [recipients replaceObjectAtIndex:0 withObject:@"?"];
    }
    
    [composeViewController setRecipients:recipients];
}

[self.viewController presentViewController:composeViewController animated:YES completion:nil];
});
```

**Comment by dbaq** [comment] 2021-01-26 18:19
@maihannijat @TravisHeaver do you guys mind opening a PR?

**Comment by dbaq** [comment] 2021-02-17 18:52
@maihannijat 's contribution has been merged. Version 1.0.1 has been published.

**Closed as completed by dbaq** 2021-02-17 18:52 UTC
