### ISSUE TITLE
彩信

### ISSUE THREAD

**Issue by Adam23Yuan** [cordova-sms/cordova-sms-plugin#143] opened 2017-09-13 08:45 UTC
本插件是否支持发送彩信

**Comment by dbaq** [comment] 2017-09-13 20:25
Hi @Dawn2Yuan,

No the plugin does not support MMS yet, please look at #14. I am closing this one since it is a duplicate of #14.

-----
Translation powered by Google Translate

嗨@ Dawn2Yuan，

没有插件不支持彩信，请看＃14。 我关闭这个，因为它是＃14的重复。

**Closed as completed by dbaq** 2017-09-13 20:25 UTC
Labels: question
