### ISSUE TITLE
App crash when using sms.send without intent Android 8

### ISSUE THREAD

**Issue by Shadowfita** [cordova-sms/cordova-sms-plugin#172] opened 2018-06-16 02:50 UTC
Hi,

when using sms.send with intent '' the app crashes but when used with 'INTENT' (where it opens the users sms app) it does not. This kind of defeats the purpose of my app. Does anyone have a work around?

Thanks!

**Comment by dbaq** [comment] 2018-06-18 15:53
hey @Shadowfita,

Can you please copy/paste the logcat logs (use `$ adb logcat`)? It will help us find the root cause of the crash.

Thank you.

**Comment by samithaC** [comment] 2018-07-13 05:58
Hi everyone,

i was using this plugin to read the SMS in my application. But i'm also facing this issues when its come andorid 8. this was working fine in the android. can't understand what is happening. i have added the error logs in bellow


> 07-13 11:18:11.225 21230-21230/lk.sampath.iwallet W/cr_AwContents: WebView.destroy() called while WebView is still attached to window.
07-13 11:18:11.266 21230-21292/lk.sampath.iwallet E/chromium: [ERROR:gl_context_virtual.cc(39)] Trying to make virtual context current without decoder.
07-13 11:18:11.309 21230-21230/lk.sampath.iwallet W/cr_AwContents: Application attempted to call on a destroyed WebView
                                                                   java.lang.Throwable
                                                                       at org.chromium.android_webview.AwContents.f(PG:311)
                                                                       at org.chromium.android_webview.AwContents.a(PG:283)
                                                                       at org.chromium.android_webview.AwContents.q(PG:530)
                                                                       at aln.loadingStateChanged(PG:160)
                                                                       at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                                       at org.chromium.base.SystemMessageHandler.handleMessage(PG:9)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                       at android.os.Looper.loop(Looper.java:251)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6572)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

>

**Comment by samithaC** [comment] 2018-07-13 05:59
Hi everyone,

i was using this plugin to read the SMS in my application. But i'm also facing this issues when its come andorid 8. this was working fine in the android. can't understand what is happening. i have added the error logs in bellow


> 07-13 11:18:11.225 21230-21230/lk.xxx.com W/cr_AwContents: WebView.destroy() called while WebView is still attached to window.
07-13 11:18:11.266 21230-21292/lk.xxx.com E/chromium: [ERROR:gl_context_virtual.cc(39)] Trying to make virtual context current without decoder.
07-13 11:18:11.309 21230-21230/lk.xxx.com W/cr_AwContents: Application attempted to call on a destroyed WebView
                                                                   java.lang.Throwable
                                                                       at org.chromium.android_webview.AwContents.f(PG:311)
                                                                       at org.chromium.android_webview.AwContents.a(PG:283)
                                                                       at org.chromium.android_webview.AwContents.q(PG:530)
                                                                       at aln.loadingStateChanged(PG:160)
                                                                       at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                                       at org.chromium.base.SystemMessageHandler.handleMessage(PG:9)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                       at android.os.Looper.loop(Looper.java:251)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6572)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

>

**Comment by samithaC** [comment] 2018-07-13 06:14
Hi everyone,

i was using this plugin to read the SMS in my application. But i'm also facing this issues when its come andorid 8. this was working fine in the android. can't understand what is happening. i have added the error logs in bellow

> 07-13 11:18:10.964 21230-21321/lk.xxx.com E/AndroidRuntime: FATAL EXCEPTION: JavaBridge
                                                                    Process: lk.xxx.com, PID: 21230
                                                                    java.lang.SecurityException: Permission Denial: reading com.android.providers.telephony.SemcSmsProvider uri content://sms/inbox from pid=21230, uid=10300 requires android.permission.READ_SMS, or grantUriPermission()
                                                                        at android.os.Parcel.readException(Parcel.java:1959)
                                                                        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
                                                                        at android.content.ContentResolver.query(ContentResolver.java:756)
                                                                        at android.content.ContentResolver.query(ContentResolver.java:705)
                                                                        at android.content.ContentResolver.query(ContentResolver.java:663)
                                                                        at com.rjfun.cordova.sms.SMSPlugin$3.onChange(SourceFile:393)
                                                                        at android.database.ContentObserver.onChange(ContentObserver.java:145)
                                                                        at android.database.ContentObserver$NotificationRunnable.run(ContentObserver.java:216)
                                                                        at android.os.Handler.handleCallback(Handler.java:789)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                        at android.os.Looper.loop(Looper.java:251)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:65)



> 07-13 11:18:11.225 21230-21230/lk.xxx.com W/cr_AwContents: WebView.destroy() called while WebView is still attached to window.
07-13 11:18:11.266 21230-21292/lk.xxx.com E/chromium: [ERROR:gl_context_virtual.cc(39)] Trying to make virtual context current without decoder.
07-13 11:18:11.309 21230-21230/lk.xxx.com W/cr_AwContents: Application attempted to call on a destroyed WebView
                                                                   java.lang.Throwable
                                                                       at org.chromium.android_webview.AwContents.f(PG:311)
                                                                       at org.chromium.android_webview.AwContents.a(PG:283)
                                                                       at org.chromium.android_webview.AwContents.q(PG:530)
                                                                       at aln.loadingStateChanged(PG:160)
                                                                       at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                                       at org.chromium.base.SystemMessageHandler.handleMessage(PG:9)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                       at android.os.Looper.loop(Looper.java:251)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6572)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

>

**Comment by dbaq** [comment] 2018-08-06 19:51
Well, it looks like you have a permission issue `Permission Denial: reading`. Have you tried on other devices? It could be your default SMS app that causes the issue.

**Comment by dbaq** [comment] 2018-08-06 19:55
It looks like this issue is a duplicate of https://github.com/cordova-sms/cordova-sms-plugin/issues/147. If not, feel free to reopen it.

**Closed as completed by dbaq** 2018-08-06 19:55 UTC
Labels: needs reply, android
