### ISSUE TITLE
cordova-sms-plugin

### ISSUE THREAD

**Issue by dipti-mahajan** [cordova-sms/cordova-sms-plugin#59] opened 2015-10-29 09:44 UTC
https://github.com/cordova-sms/cordova-sms-plugin 
I installed the plugin very much correctly. The cordova version i m using is 2.8.

First i got error as "uncaught reference error - module not defined" then in sms.js file i defined the module as var module={}; which resolved that error. But then i m getting another error.

The new error i m getting is "uncaught reference error - SMS not defined". I request you to please help me. I m struglling with this sms plugin since last two days and till no output. Error is coming at this line.

  sms.send(number, message, options, success, error);

Any help will be much appreciated.

**Comment by nikunj17287** [comment] 2015-10-29 10:41
Dipti i guess the issue is due to wrong usage of sms.send initially i was also getting similar error.
Also i am not sure if cordova version 2.8 is supported. I am using version 5.3.3 for cordova and 1.0.4 for SMS Plugin

Replaced with below code and it worked fine.

SMS.sendSMS(number, msgStr, options, success, error );

however i am getting an info msg 

[INFO:CONSOLE(310)] "Error in Success callbackId: SMS1053728464 : TypeError: callback.success.apply is not a function", source: file:///android_asset/www/cordova.js (310) [INFO:CONSOLE(291)] "Uncaught (in promise) TypeError: callback.success.apply is not a function", source: file:///android_asset/www/cordova.js (291)

which i suspect is due to non-support of dual sim mobile. as its works just perfectly in Single sim phone.

**Comment by dipti-mahajan** [comment] 2015-10-29 10:54
Hi Nikunj,
Thanks. Tried but failed. Same Error.

10-29 16:23:46.564: D/CordovaLog(29816): file:///android_asset/www/html/callinfo/callinfo.html: Line 21 : Uncaught ReferenceError: SMS is not defined

**Comment by dbaq** [comment] 2015-11-07 18:41
@dipti-mahajan did you figure it out?

**Comment by dbaq** [comment] 2015-12-12 18:07
Closing this one since it has been more than 1 month. Feel free to reopen it if you still have an issue.

**Closed as completed by dbaq** 2015-12-12 18:07 UTC
Labels: question
